version: "3.3"
services:
  mongodb:
    image: mongo
    container_name: mongodb
    networks:
      - app-network
    volumes:
      - ~/database:/data/db
    restart: unless-stopped
    
  server:
    image: pranav243/spe_main_project_server
    container_name: server
    ports:
      - '3001:3001'
    restart: unless-stopped
    networks:
      - app-network
    volumes:
      - /home/pranav/Desktop/SPE_FINAL/app.log
  client:
    image: pranav243/spe_main_project_client
    container_name: client
    ports:
      - '3000:3000'
    restart: unless-stopped
    networks:
      - app-network

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.10
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    networks:
      - app-network
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"

  logstash:
    image: docker.elastic.co/logstash/logstash:7.17.10
    container_name: logstash
    volumes:
      - /home/pranav/Desktop/SPE_FINAL/app.log:/app/app.log
      - /home/pranav/Desktop/SPE_FINAL/logstash.conf:/usr/share/logstash/pipeline/logstash.conf:ro
    environment:
      - xpack.monitoring.enabled=false
    networks:
      - app-network
    depends_on:
      - elasticsearch
    ports:
      - "5044:5044"

  kibana:
    image: docker.elastic.co/kibana/kibana:7.17.10
    container_name: kibana
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    networks:
      - app-network
    depends_on:
      - elasticsearch
    ports:
      - "5601:5601"

networks:
  app-network:
    driver: bridge

volumes:
  node_modules:
  elasticsearch-data:
    driver: local
