- name: Deploying with Kubernetes
  hosts: all
  tasks:
    - name: Show ansible_user
      debug:
        msg: "The ansible_user is {{ ansible_user }}"

    - name: Clone the repository
      git:
        repo: https://github.com/arjun-subhedar/SPE_FINAL
        dest: /tmp/SPE_FINAL
      

    - name: Apply Kubernetes manifests
      command: kubectl apply -f /tmp/SPE_FINAL/kub --insecure-skip-tls-verify --validate=false